mads.exe RUSHHOURRACE.ASM -d:EASY -o:RUSHHOURRACE_EASY.XEX -t:RUSHHOURRACE_EASY.lab -l:RUSHHOURRACE_EASY.lst
mads.exe RUSHHOURRACE.ASM -d:NORMAL -o:RUSHHOURRACE_NORMAL.XEX -t:RUSHHOURRACE_NORMAL.lab -l:RUSHHOURRACE_NORMAL.lst
mads.exe RUSHHOURRACE.ASM -d:HARD -o:RUSHHOURRACE_HARD.XEX -t:RUSHHOURRACE_HARD.lab -l:RUSHHOURRACE_HARD.lst
